### ISSUE TITLE
Fails to load coverage log produced by Frida

### ISSUE THREAD

**Issue by Ayrx** [gaasedelen/lighthouse#44] opened 2018-10-14 09:36 UTC
Hi, it seems like there is a bug when loading the coverage file produced by the Frida script. I know it's experimental but you may be interested in fixing it. :)

```
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/ida_integration.py", line 234, in activate
    self.action_function()
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/core.py", line 321, in interactive_load_file
    created_coverage, errors = self.director.create_coverage_from_drcov_list(drcov_list)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/director.py", line 439, in create_coverage_from_drcov_list
    if coverage.suspicious:
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/coverage.py", line 210, in suspicious
    percent = (bad/float(total))*100
ZeroDivisionError: float division by zero
```

The coverage data produced by PIN loads fine on the same executable. It is a simple C test program compiled to a Mach-O executable.

```c
#include <stdio.h>
#include <string.h>

void main(int argc, char** argv) {

	char foo[20];
	gets(foo);

	if (strcmp(foo, "a") == 0) {
		printf("foo\n");
	} else {
		printf("bar\n");
	}
}
```

I've attached the failing `frida-cov.log` file.

[frida-cov.log](https://github.com/gaasedelen/lighthouse/files/2476238/frida-cov.log)

**Comment by gaasedelen** [comment] 2018-10-15 16:01
Good catch!

The first issue is that Frida did not really capture *any* coverage. If you open the log in a text editor, you'll see that it is virtually empty. This could be a Frida compatibility issue with macOS or maybe a regression in `frida-cov.py`. As you have noted, there's a reason it is marked experimental 😛 

The second issue (the crashing callstack) is indeed a Lighthouse bug that will need to be fixed. It's an edge case that manifested as a result of no coverage getting loaded from an empty log. 

Since this isn't critical, I'll push a fix to dev for now. It may get included in a minor patch/hotfix to master in the coming weeks.

**Comment by Ayrx** [comment] 2018-10-16 13:43
Thanks for the quick fix!

Yeah, the lack of coverage appears to be a Frida Stalker issue. I'm trying to work out a fix and I'll send a PR if I do manage to figure out what the issue is.

**Comment by yrp604** [comment] 2018-10-25 08:38
Hey,

So the behaviour you're seeing from frida-drcov.py is unfortunate and we should maybe add some warnings about, but it's unlikely that we can fix it. To understand whats happening, some super brief Frida basics: Frida works by by injecting a thread into the target, then using that thread to instrument the other threads in the process (this is part of the reason why Frida must attached after a process is started). Once frida is running, the js thread collects data and IPC's it to the python script, which then collects and formats/persists it on exit.

The issue you're seeing is basically a race condition: when your test program calls `exit()`, all threads are getting torn down, including the frida thread before it's IPC'd out its events. We can see this pretty clearly if we modify the test program to include a call to `sleep()`:

```C
#include <stdio.h>
#include <string.h>
#include <unistd.h>

int main(int argc, char** argv) {
	char foo[20];
	gets(foo);

	if (strcmp(foo, "a") == 0) {
		printf("foo\n");
	} else {
		printf("bar\n");
	}

	sleep(1); // XXX add sleep
}
```

Now when we run the frida script:
```
ahorsewithnoname:lighthouse-bug x$ ./frida-drcov.py foobar
[*] Attaching to pid '6877' on device 'local'...
[+] Attached. Loading script...
[+] Got module info.
Starting to stalk threads...
Stalking thread 775.
Done stalking threads.
[*] Now collecting info, control-D to terminate....
[*] Detaching, this might take a second...
[+] Detached. Got 560 basic blocks.
[*] Formatting coverage and saving...
[!] Done
```

We get the expected coverage. To fix this we would need to make frida-drcov.py OS aware, so it could register clean up hooks for each target and have the js side flush the events before terminating (i.e. `atexit()` and friends). I'm pretty unlikely to do this for a few reasons: it would really increase the complexity of the otherwise pretty simple script and I don't have the hardware or desire to test/port this to all the OS's that Frida supports.

This puts the frida script in kinda a weird spot -- it works pretty well for larger targets that you want to attach, trace, and detach from but pretty poorly for short lived tests that exit. Thankfully, in most of the cases where you'll actually want to use frida-drcov.py you're more likely to be in the former category. I think the best we can do in this case is just more clearly document the shortcomings of this script.

**Comment by Ayrx** [comment] 2018-10-26 08:35
I will look into it when I can as well and update here if I find anything new.

**Comment by gaasedelen** [comment] 2018-11-06 19:36
Closing this as Frida now has the fix in-box :-)

**Closed by gaasedelen** 2018-11-06 19:36 UTC
Labels: bug
