### ISSUE TITLE
Lighthouse cannot parse log files generated by drcov-2

### ISSUE THREAD

**Issue by PaDarochek** [gaasedelen/lighthouse#124] opened 2022-07-28 16:09 UTC
I'm trying to explore the code coverage with Lighthouse but every time I load the log file generated by drcov tool I get PARSE_FAILURE error message. My drcov version is 2.  

I've tried different Lighthouse and Dynamorio releases but it didn't work. I got this error on each log file I try to load to IDA, it looks like in the image below:
![Screenshot from 2022-07-28 19-04-09](https://user-images.githubusercontent.com/69221349/181585381-59f52eca-18d6-4443-92cd-9b13d7597151.png)  

Please help me with this issue

**Comment by wumb0** [comment] 2022-08-04 17:37
duplicate of #112. i posted a temp fix there.

**Comment by PaDarochek** [comment] 2022-08-05 21:21
@wumb0 I checked that drcov is v2, but still not working. I attach the coverage file below:
[drcov.log](https://github.com/gaasedelen/lighthouse/files/9272764/drcov.log)

**Comment by wumb0** [comment] 2022-08-05 22:05
I'd expect there to be binary data at the bottom of the file, not another table
```
module id, start, size:
module[  4]: 0x0000000000001090,   8
module[  4]: 0x0000000000001ea0,  85
module[  4]: 0x0000000000001ef5,  65
module[  4]: 0x0000000000001f5b,   6
module[  4]: 0x0000000000001f4b,  16
```
I'm not sure that's valid. What flags did you pass to drrun/drcov to get it to generate this output?
I can probably write a quick converter for this format to work with lighthouse.

**Comment by wumb0** [comment] 2022-08-05 22:26
```python
import ctypes
import sys
import re


'''
// Data structure for the coverage info itself
typedef struct _bb_entry_t {
    uint   start;      // offset of bb start from the image base
    ushort size;
    ushort mod_id;
} bb_entry_t;
'''
class bbs_entry(ctypes.Structure):
    _fields_ = [
        ('start', ctypes.c_uint32),
        ('size', ctypes.c_uint16),
        ('mod_id', ctypes.c_uint16)
    ]


content = open(sys.argv[1]).readlines()
for i, line in enumerate(content):
    if line.startswith("BB Table: "):
        idx = i

table = content[idx+2:]
head = "".join(content[:idx+1]).encode()
reg = re.compile(r"module\[(\s+)?(\d+)\]:\s+0x([a-fA-F0-9]+),\s+(\d+)")
out_table = b""
for ent in table:
    # module[  4]: 0x0000000000001090,   8
    if not ent.startswith("module"):
        continue
    match = reg.match(ent)
    if not match:
        raise Exception(f"Failed to parse: {ent}")
    _, mid, start, size = match.groups()
    bb = bbs_entry(int(start, 16), int(size), int(mid))
    out_table += bytes(bb)

with open(sys.argv[1]+".fixed", "wb") as w:
    w.write(head)
    w.write(out_table)
```

Try that maybe?

**Comment by PaDarochek** [comment] 2022-08-06 22:48
@wumb0 I used DynamoRIO 7.1.0 release and run drrun this way:
dynamorio/bin64/drrun -t drcov -dump-text -logdir out_dir -- prog args

Thanks a lot for your converter, it helped me to fix the issue!

**Closed** 2022-08-07 20:38 UTC
