### ISSUE TITLE
Error: PARSE_FAILURE

### ISSUE THREAD

**Issue by maskelihileci** [gaasedelen/lighthouse#101] opened 2021-04-15 06:14 UTC
DynamoRIO-Windows-8.0.0-1 : I tested in this version

I added the example below, I would be glad if you can look.
[drcov.Patcher.exe.03104.0000.proc.log]
(https://github.com/gaasedelen/lighthouse/files/6315503/drcov.Patcher.exe.03104.0000.proc.log)

**Comment by maskelihileci** [comment] 2021-04-15 20:33
Now I am trying intel pin which pin version is compatible with this is not specified

So I couldn't compile codecoverage please can you send the compiled version to me and also compatible pin

**Comment by gaasedelen** [comment] 2021-04-23 07:22
Thanks for attaching a log file. 

I took a look at it. The problem is that your log file is technically corrupt. It states that it should have 340k entries in the BB table, while the file actually only contains 190k or so. 

```
...
BB Table: 340108 bbs
...
```

So yes. It is a parse failure because the log is malformed.

I could technically change this to load what it can, but maybe it's for the best that it crashed? We know now that your log file is incomplete, and that it wouldn't be showing you the true results of your run. 

I'm going to close this for now cuz it's not a Lighthouse bug. But I'll think about whether this is something I should change in the future.

**Closed by gaasedelen** 2021-04-23 07:22 UTC

**Comment by maskelihileci** [comment] 2021-04-23 21:25
Thank you for answering the question
I solved the problem by downgrading the DynamoRIO version
But the software did not fully meet my needs.

Arranging functions regularly, starting from the entry point.
we can see where the function goes at the turning point
Not seeing the biggest missing record values

Misunderstanding I just wanted to point out the missing features if you want to improve this program in the future.
Thanks for the software



Working version : DynamoRIO-Windows-8.0.18471
