### ISSUE TITLE
Dynamorio 

### ISSUE THREAD

**Issue by dhucul** [gaasedelen/lighthouse#113] opened 2022-01-03 23:53 UTC
DynamoRio version 9.  Error: PARSE_FAILURE in Ida Pro.

**Comment by wumb0** [comment] 2022-08-04 17:36
duplicate of #112 i posted a temp fix there.

**Comment by gaasedelen** [comment] 2024-01-19 00:50
#137 has been merged into the develop branch, fixing this issue.

**Closed by gaasedelen** 2024-01-19 00:50 UTC
